[phases.setup]
nixPkgs = ["libGL", "glib", "gcc-unwrapped", "libxcb", "xorg.libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libXau", "libsm6", "libxext6", "libx11"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"
