[phases.setup]
nixPkgs = ["libGL", "glib", "gcc-unwrapped", "libxcb", "libx11", "libXrender", "libXext", "libsm6", "libxext6"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"
