[phases.setup]
nixPkgs = [
  "libGL",
  "glib",
  "gcc-unwrapped",
  "zlib",
]

[phases.setup.aptPkgs]

packages = ["libglib2.0-0", "libgl1-mesa-glx"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT"
